name: learning_hub

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd /Users/admin/learning_hub

          git fetch origin
          git reset --hard origin/production

          pnpm install
          pnpm build

          pm2 reload learning_hub || pm2 start ecosystem.config.js
